// CREATE USER
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Mileny",
    "email": "myrfaria@gmail.com",
    "password": "123456"
}

###
// GET USERS
GET http://localhost:3003/users

###
// POST PRODUCT
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "MILLENIUM FALCON",
    "price": 999.00,
    "image_url": "https://s2.glbimg.com/coHwdDkMeRVO9T2A_v1EIWLuHTE=/e.glbimg.com/og/ed/f/original/2019/08/27/31618033034_1dcde167ed_k.jpg"
}

###
// GET PRODUCTS
GET http://localhost:3003/products


###
// POST PURCHASE
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "user_id": "7724dcb0-64e6-41f2-ad0d-87f98b88ba49",
    "product_id": "ac4cbf15-ee72-42b5-baac-0419b1434646",
    "quantity": 2
}


###
// GET USER PURCHASES
GET http://localhost:3003/users/7724dcb0-64e6-41f2-ad0d-87f98b88ba49/purchases