// CREATE USER
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Mileny",
    "email": "mileny@gebru.com",
    "password": "123456"
}

###
// GET USERS
GET http://localhost:3003/users