// signup
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Gelson",
    "email": "gelson@gmail.com",
    "password": "pass123"
}

###

// login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "mileny@gmail.com",
    "password": "pass123"
}

###

// get profile
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTgzYTA4LTQxNzctNGQyOS04ZjA4LTk2OTAwMjk2ZDdhNSIsImlhdCI6MTY2MTgxMDE1NywiZXhwIjoxNjYxODEzNzU3fQ.eubTTG12GxE1T3StkeHaFvP5UAScr_Z1KWgBNcHoNTQ

###

// get profile by id
GET http://localhost:3003/user/profile/39fb9da2-7a51-4c57-a8a9-db02c2e765d7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTgzYTA4LTQxNzctNGQyOS04ZjA4LTk2OTAwMjk2ZDdhNSIsImlhdCI6MTY2MTgxMDE1NywiZXhwIjoxNjYxODEzNzU3fQ.eubTTG12GxE1T3StkeHaFvP5UAScr_Z1KWgBNcHoNTQ

###

// create recipe
POST http://localhost:3003/recipe/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTgzYTA4LTQxNzctNGQyOS04ZjA4LTk2OTAwMjk2ZDdhNSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjE4MTQ1MjgsImV4cCI6MTY2MTgxODEyOH0.j3WJn8usEBsbrbfkhkglVeDoi-tdfB3T77Kl1G7b8Fo

{
    "title": "CEVICHE DE TILÁPIA",
    "preparationMode": "Corte os filés de tilápia em pequenos cubos. Fatie a cebola finamente. Descarte as sementes da pimenta e fatie bem fininha. Coloque o peixe, a cebola, o milho e a pimenta em um recipiente, acrescente o sal e misture bem. Acrescente o suco dos limões e leve à geladeira por cerca de uma hora. Na hora de servir, acrescente o tomate cortado em cubinhos, o coentro (ou salsa) e um fio de azeite."
}

###

// get recipe by id
GET http://localhost:3003/recipe/9d408b88-eb46-4b3b-9d4d-96a012978aa4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTgzYTA4LTQxNzctNGQyOS04ZjA4LTk2OTAwMjk2ZDdhNSIsImlhdCI6MTY2MTgxMDA0NywiZXhwIjoxNjYxODEzNjQ3fQ.s2qQekZzbj57fHTV4kS2_snRkM2FkfoxNBgcmqnXrS8

###

// edit recipe
PUT http://localhost:3003/recipe/edit/c142d4d4-92c0-4b04-aa4f-adf4e023c1cd
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTgzYTA4LTQxNzctNGQyOS04ZjA4LTk2OTAwMjk2ZDdhNSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjE4MTQ2MzYsImV4cCI6MTY2MTgxODIzNn0.NVUJHLfrWbH6D5ELSU73CUzPUwOfzPjU1By1cr9C-QU

{
    "preparationMode": "Corte os filés de tilápia em pequenos cubos. Fatie a cebola finamente. Descarte as sementes da pimenta e fatie bem fininha. Coloque o peixe, a cebola, o milho e a pimenta em um recipiente, acrescente o sal e misture bem. Acrescente o suco dos limões e leve à geladeira por cerca de uma hora. Na hora de servir, acrescente o tomate cortado em cubinhos, o coentro (ou salsa) e um fio de azeite."
}

###

// delete recipe
DELETE http://localhost:3003/recipe/delete/c142d4d4-92c0-4b04-aa4f-adf4e023c1cd
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTgzYTA4LTQxNzctNGQyOS04ZjA4LTk2OTAwMjk2ZDdhNSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjE4MTU3NDgsImV4cCI6MTY2MTgxOTM0OH0.uYeGgsHpB99zm8JH7SgYXu-8jDZq3CBlUnBPbc_iRvo

###

// make friends
POST http://localhost:3003/user/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTgzYTA4LTQxNzctNGQyOS04ZjA4LTk2OTAwMjk2ZDdhNSIsImlhdCI6MTY2MTgxMjg0MCwiZXhwIjoxNjYxODE2NDQwfQ.DSUT_3yU-fHvMzOvdH2PoytExbonVuF4OA6IBit74C0

{
"friendId": "39fb9da2-7a51-4c57-a8a9-db02c2e765d7"
}

###

// unfollow
POST http://localhost:3003/user/unfollow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTgzYTA4LTQxNzctNGQyOS04ZjA4LTk2OTAwMjk2ZDdhNSIsImlhdCI6MTY2MTgxMjg0MCwiZXhwIjoxNjYxODE2NDQwfQ.DSUT_3yU-fHvMzOvdH2PoytExbonVuF4OA6IBit74C0

{
"friendId": "39fb9da2-7a51-4c57-a8a9-db02c2e765d7"
}

###